alias kimi='command kimi --yolo'
alias codex='command codex --yolo'
alias claude='command claude --dangerously-skip-permissions'
alias cluade='command claude --dangerously-skip-permissions'
alias na='nautilus . &>/dev/null &'
