set -g mouse on
set -g mode-keys vi

set -g prefix C-a
bind C-a send-prefix

# improve colors; use tmux-256color if available, otherwise install ncurses-term
set -g default-terminal 'tmux-256color'
set -as terminal-overrides ',xterm-256color:RGB'

# simplify status-right
set -g status-right '%H:%M %d-%b-%y'
set -g status-right-length 20

# let app know focus-event
set -g focus-events on

# kimi-code required
set -g extended-keys on
